name: Deploy on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: secrets
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure the entire history is fetched, required for private repositories

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Authenticate with GitHub
      run: |
        git config --global credential.helper '!f() { sleep 1; echo "username=${{ secrets.GIT_USER }}"; echo "password=${{ secrets.GIT_PASS }}"; }; f'

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASS }}
        port: 22
        script: |
          whoami

