name: Deploy on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SSH
#    env:
#      SSH: ${{ env.SSH }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.ssh_USER }}
        key: ${{ env.ssh_KEY }}
        password: ${{ env.ssh_PASS }}
        port: 22
        script: whoami
