name: Deploy on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        passphrase: ${{ env.SSH_PASS }}
  
